### ISSUE TITLE
Build-error in Windows & FTGL/Freetype dependency

### ISSUE THREAD

**Issue by gjdv** [pianobooster/PianoBooster#23]
I'm trying to build in Windows using QT (version 5.12.1; MinGW 7.3.0) and CMake (version 3.13.3), following the instructions in BUILD.txt

The first part (`"C:\Program Files\CMake\bin\cmake.exe" -G "MinGW Makefiles" .`; note that CMake does not (anymore) use a version number in its path) works as it should. After that, I already found out that rather than calling `make` I should call:
`cmake --build . --target install --config RELEASE`

However, it complains that it cannot find ftgl:
```
D:\Coding\PianoBooster>cmake --build . --target install --config RELEASE
[  2%] Automatic MOC and UIC for target pianobooster
[  2%] Built target pianobooster_autogen
[  4%] Building CXX object build/CMakeFiles/pianobooster.dir/QtMain.obj
In file included from D:\Coding\PianoBooster\src\Scroll.h:33:0,
                 from D:\Coding\PianoBooster\src\Score.h:34,
                 from D:\Coding\PianoBooster\src\QtWindow.h:33,
                 from D:\Coding\PianoBooster\src\QtMain.cpp:27:
D:\Coding\PianoBooster\src\Draw.h:38:10: fatal error: FTGL/ftgl.h: No such file or directory
 #include <FTGL/ftgl.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

After downloading from [FTGL](https://sourceforge.net/projects/ftgl/) and copying the `src/FTGL` directory to the `src` directory of PianoBooster I get the following error:

```
D:\Coding\PianoBooster>cmake --build . --target install --config RELEASE
[  2%] Automatic MOC and UIC for target pianobooster
[  2%] Built target pianobooster_autogen
[  4%] Building CXX object build/CMakeFiles/pianobooster.dir/QtMain.obj
In file included from D:\Coding\PianoBooster\src\Draw.h:38:0,
                 from D:\Coding\PianoBooster\src\Scroll.h:33,
                 from D:\Coding\PianoBooster\src\Score.h:34,
                 from D:\Coding\PianoBooster\src\QtWindow.h:33,
                 from D:\Coding\PianoBooster\src\QtMain.cpp:27:
D:/Coding/PianoBooster/src/FTGL/ftgl.h:32:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
```
After downloading from [Freetype](https://sourceforge.net/projects/freetype/) and copying the contents of the `include` directory to the `src` directory of PianoBooster, the code does compile a little further, until:
```
[ 72%] Building RC object build/CMakeFiles/pianobooster.dir/pianobooster.obj
C:\Qt\Tools\mingw730_64\bin\windres.exe: unknown option -- W
```

Following [the suggestion here](https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows) I uncheck the option ENABLE_PRECOMPILED_HEADERS by calling:
```
"C:\Program Files\CMake\bin\cmake.exe" -DENABLE_PRECOMPILED_HEADERS=OFF -G "MinGW Makefiles" .
```  

However, that does not seem to have any effect.

Can anyone help me build in Windows?

**Comment by glixx** [comment]
Should be fixed by https://github.com/captnfab/PianoBooster/pull/30/commits/f967a7ef4db49bfd93f70d7ea55f1fade58d3261
No more dependency on font.

**Comment by gjdv** [comment]
Thanks for the update. I've tried with the latest revision of admsasha, but still having some issues:

`g++ -Wl,-s -Wl,-subsystem,windows -mthreads -o release\pianobooster.exe @object_script.pianobooster.Release  -lwinmm -LC:\Qt\5.12.1\mingw73_64\lib C:\Qt\5.12.1\mingw73_64\lib\libQt5OpenGL.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Widgets.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Gui.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Xml.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Core.a tmp\pianobooster_res.o  -lmingw32 C:\Qt\5.12.1\mingw73_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.6.11-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 -LC:\Qt\5.12.1\mingw73_64\lib C:\Qt\5.12.1\mingw73_64\lib\libQt5Core.a 
tmp/GlView.o:GlView.cpp:(.text+0x2cc): undefined reference to '__imp_glColor3f'
tmp/GlView.o:GlView.cpp:(.text+0x70d): undefined reference to '__imp_glColor3f'
...`

Looks like dependency on glut. I'll try to find some time to look into this later today.

**Comment by gjdv** [comment]
Still didn't resolve the issue.
[This forum topic](https://forum.qt.io/topic/97484/qt-5-12-make-mingw-32-release/2) suggests that similar issues were caused by a mixup of x64 and x86 and that a solution might be to use Qt 5.11 to be able to use 32bit versions of all components only. However, that did not resolve the problem.
I'm still stuck at this output:

`windres -i ..\src\pianobooster.rc -o tmp\pianobooster_res.o --include-dir=./../src -DUNICODE -D_UNICODE -DWIN32 -D__WINDOWS_MM__ -D_WIN32 -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN
g++ -Wl,-s -Wl,-subsystem,windows -mthreads -o release\pianobooster.exe object_script.pianobooster.Release  -lmingw32 -LC:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib C:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.6.11-win32\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 -lwinmm C:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib\libQt5OpenGL.a C:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib\libQt5Widgets.a C:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib\libQt5Gui.a C:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib\libQt5Xml.a C:\Qt\Qt5.11.1\5.11.1\mingw53_32\lib\libQt5Core.a tmp\pianobooster_res.o 
./tmp\GlView.o:GlView.cpp:(.text+0x20a): undefined reference to `_imp__glColor3f@12'
./tmp\GlView.o:GlView.cpp:(.text+0x637): undefined reference to `_imp__glColor3f@12'
./tmp\GlView.o:GlView.cpp:(.text+0x663): undefined reference to `_imp__glRectf@16'
./tmp\GlView.o:GlView.cpp:(.text+0x6f6): undefined reference to `_imp__glLineWidth@4'
./tmp\GlView.o:GlView.cpp:(.text+0x722): undefined reference to `_imp__glBegin@4'
./tmp\GlView.o:GlView.cpp:(.text+0x72b): undefined reference to `_imp__glVertex2f@8'
./tmp\GlView.o:GlView.cpp:(.text+0x78a): undefined reference to `_imp__glEnd@0'
./tmp\GlView.o:GlView.cpp:(.text+0x812): undefined reference to `_imp__glColor3f@12'
./tmp\GlView.o:GlView.cpp:(.text+0x8d9): undefined reference to `_imp__glColor3f@12'
./tmp\GlView.o:GlView.cpp:(.text+0xba5): undefined reference to `_imp__glColor3f@12'
...`

**Comment by admsasha** [comment]
I have a successful build through both qmake and cmake. How do you compile?
I use Qt version 5.12.1 (for mingw32)

try for qmake added in pianobooster.pro
Qt += -lopengl32
or for cmake in src/CMakeLists.txt
add_compile_options(-lopengl32)

**Comment by gjdv** [comment]
Thanks for your help. I've tried multiple things
In any case I need to add the following items to the PianoBooster/src directory to get some compilation (see my initial post for sources):

- FTGL/*
- freetype/*
- ft2build.h

This resolves the following initial errors:
```
 ..\src\Draw.h:38:10: fatal error: FTGL/ftgl.h: No such file or directory
 #include <FTGL/ftgl.h>
```
and 
```
 ..\src/FTGL/ftgl.h:32:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
```

Now, compiling with Qt version 5.12.1 with MinGW 7.3.0:

1. QT Creator version 4.8.2, building pianobooster.pro yields:
```
 ...
 g++ -Wl,-s -Wl,-subsystem,windows -mthreads -o release\pianobooster.exe @object_script.pianobooster.Release  -lwinmm -LC:\Qt\5.12.1\mingw73_64\lib C:\Qt\5.12.1\mingw73_64\lib\libQt5OpenGL.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Widgets.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Gui.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Xml.a C:\Qt\5.12.1\mingw73_64\lib\libQt5Core.a tmp\pianobooster_res.o  -lmingw32 C:\Qt\5.12.1\mingw73_64\lib\libqtmain.a -LC:\openssl\lib -LC:\Utils\my_sql\mysql-5.6.11-winx64\lib -LC:\Utils\postgresql\pgsql\lib -lshell32 -LC:\Qt\5.12.1\mingw73_64\lib C:\Qt\5.12.1\mingw73_64\lib\libQt5Core.a 
tmp/QtMain.o:QtMain.cpp:(.text+0x29): undefined reference to `_imp___ZN12QApplicationC1ERiPPci'
tmp/QtMain.o:QtMain.cpp:(.text+0x32): undefined reference to `_imp___ZN9QGLFormat9hasOpenGLEv'
tmp/QtMain.o:QtMain.cpp:(.text+0x4b): undefined reference to `_imp___ZN7QWidget4showEv'
tmp/QtMain.o:QtMain.cpp:(.text+0x51): undefined reference to `_imp___ZN12QApplication4execEv'
...
```

2. CMake (ensuring there is a environment variable named CMAKE_PREFIX_PATH, with value C:\Qt\5.12.1\mingw73_64):
Calling `"C:\Program Files\CMake\bin\cmake.exe" -G "MinGW Makefiles" .`, followed by `cmake --build . --config Release` (instead of  `make`) yields:
```
...
[ 78%] Linking CXX executable pianobooster.exe
CMakeFiles\pianobooster.dir/objects.a(Score.obj):Score.cpp:(.text+0xc85): undefined reference to `FTPixmapFont::FTPixmapFont(char const*)'
CMakeFiles\pianobooster.dir/objects.a(Score.obj):Score.cpp:(.text+0x11b5): undefined reference to `FTPixmapFont::FTPixmapFont(char const*)'
CMakeFiles\pianobooster.dir/objects.a(Score.obj):Score.cpp:(.text+0x17dd): undefined reference to `FTPixmapFont::FTPixmapFont(char const*)'
collect2.exe: error: ld returned 1 exit status
```

Your suggestion to add `add_compile_options(-lopengl32)` to src/CMakeLists.txt did not help

**Comment by admsasha** [comment]
very strange. 
instead  SET(FTGL_LIBRARY ${FTGL_LIBRARIES})  set SET(FTGL_LIBRARY-lftgl)

**Comment by admsasha** [comment]
pkgconfig it exists and is used ?

**Comment by gjdv** [comment]
Changing the FTGL_LIBRARY line did not change anything.
Running `pkg-config --version` yields `0.26`. How do I check if it is used?
Without the dash ("pkgconfig") does not exist.

When I run `pkg-config --list-all` it does not list OpenGL. Is that correct?
```
pkg-config --list-all
bzip2      bzip2 - Lossless, block-sorting data compression
expat      expat - expat XML parser
freetype2  FreeType 2 - A free, high-quality, and portable font engine.
gdlib      gd - GD graphics library
libcrypto  OpenSSL-libcrypto - OpenSSL cryptography library
libexslt   libexslt - EXSLT Extension library
libffi     libffi - Library supporting Foreign Function Interfaces
liblzma    liblzma - General purpose data compression library
libpng     libpng - Loads and saves PNG files
libpng16   libpng - Loads and saves PNG files
libpq      libpq - PostgreSQL libpq library
libssh2    libssh2 - Library for SSH-based communication
libssl     OpenSSL-libssl - Secure Sockets Layer and cryptography libraries
libtiff-4  libtiff - Tag Image File Format (TIFF) library.
libxml-2.0 libXML - libXML library version2.
libxslt    libxslt - XSLT library version 2.
openssl    OpenSSL - Secure Sockets Layer and cryptography libraries and tools
xpm        Xpm - X Pixmap Library
zlib       zlib - zlib compression library
```

**Comment by admsasha** [comment]
```
# pacman -Sl| grep ftgl
mingw32 mingw-w64-i686-ftgl 2.1.3rc5-2 [установлен]
mingw64 mingw-w64-x86_64-ftgl 2.1.3rc5-2 [установлен]

```
```
# pkg-config --list-all|grep -i ftgl
ftgl                  FTGL - OpenGL frontend to Freetype 2
```

**Comment by gjdv** [comment]
Thanks and sorry for the delay in my answer. Looks like we are homing in to the problem.
pkg-config does not list FTGL.

After downloading [mingw-get](https://sourceforge.net/projects/mingw/files/Installer/mingw-get/) and running `mingw-get.exe install ftgl` I get the message that the package cannot be found

pacman is not available from mingw.
I did try installing MSYS2 and running pacman from there. It does output the 2 packages you listed and I am able to install them using `pacman -S mingw-w64-i686-ftgl mingw-w64-x86_64-ftgl`, however they are installed in such a way that minGW still does not know them.

Any ideas how to solve this?

**Comment by admsasha** [comment]
Try move pkg-config files ftgl to be seen mingw.

**Comment by glixx** [comment]
@admsasha built in Windows, so we have no bugs in source code.

**Comment by glixx** [comment]
Testing Windows installer: https://github.com/captnfab/PianoBooster/issues/76
